steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/anju-100959389/app:${SHORT_SHA}',
        '.'
      ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/anju-100959389/app:${SHORT_SHA}'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'anju-100959389-service',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/anju-100959389/app:${SHORT_SHA}',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
